name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  run-on-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run a sample command
        run: echo "Hello, this is a manual workflow running on ubuntu-latest!"
