name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  run-on-self-hosted:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run a sample command on self-hosted
        run: echo "This is running on a self-hosted runner!"

